# Generated by Django 5.0.2 on 2024-02-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activebreakssettings',
            name='auto_start_timer',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='activebreakssettings',
            name='notification_interval',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
