# Generated by Django 5.0.2 on 2024-03-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_activebreakssettings_auto_start_timer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activebreakssettings',
            name='auto_start_timer',
        ),
        migrations.AddField(
            model_name='activebreakssettings',
            name='auto_start_break_timer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activebreakssettings',
            name='auto_start_work_timer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activebreakssettings',
            name='notification_interval',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='activebreakssettings',
            name='work_duration',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
