# Generated by Django 5.0.2 on 2024-03-06 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_activebreakssettings_auto_start_timer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activebreakssettings',
            old_name='work_duration',
            new_name='break_timer',
        ),
        migrations.RenameField(
            model_name='activebreakssettings',
            old_name='notification_interval',
            new_name='work_timer',
        ),
    ]
