# Generated by Django 5.0.7 on 2024-07-15 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_exercise_alter_activebreakssettings_break_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannedworkout',
            name='rest_day',
        ),
    ]
